//! `--credits` and `notices` as a user and a release gate invoke them
//! (`ARCH/05-SOURCE-LEDGER.md` §4, `AX-010`).

use std::path::Path;
use std::process::Command;

fn binary() -> Command {
    Command::new(env!("CARGO_BIN_EXE_horizoncode"))
}

fn workspace_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

#[test]
fn credits_prints_the_shipped_bundle_and_needs_no_configuration() {
    let output = binary()
        .arg("--credits")
        .env_remove("HORIZONCODE_HOME")
        .env_remove("HORIZONCODE_API_KEY")
        .output()
        .unwrap();
    assert!(output.status.success(), "{:?}", output.status);
    let text = String::from_utf8(output.stdout).unwrap();
    assert!(
        text.starts_with("<!-- Generated by `horizoncode notices generate`."),
        "{}",
        &text[..text.len().min(120)]
    );
    assert!(text.contains("# Third-party notices"));
    assert!(text.contains("## Pinned dependency set"));
    assert!(text.contains("## License texts"));
    assert!(
        output.stderr.is_empty(),
        "a credits answer must not need a provider or a store: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn notices_check_confirms_the_shipped_bundle() {
    let output = binary()
        .args(["notices", "check"])
        .current_dir(workspace_root())
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        String::from_utf8_lossy(&output.stdout).contains("current"),
        "{}",
        String::from_utf8_lossy(&output.stdout)
    );
}

#[test]
fn notices_generate_round_trips_through_a_file() {
    // Generate to a temporary path and confirm it is a complete bundle; the
    // staleness gate itself is exercised by the unit tests and `notices check`.
    let dir = tempfile::tempdir().unwrap();
    let output_path = dir.path().join("THIRD-PARTY-NOTICES.md");
    let status = binary()
        .args(["notices", "generate", "--output"])
        .arg(&output_path)
        .current_dir(workspace_root())
        .status()
        .unwrap();
    assert!(status.success());
    let text = std::fs::read_to_string(&output_path).unwrap();
    assert!(text.contains("## Pinned dependency set"));
    assert!(text.len() > 1024, "a bundle with notices is not a stub");
}
