//! The Seatbelt profile the macOS tier applies (`ARCH/13` §Platform notes,
//! `DEC-026`).
//!
//! The profile text is generated by a platform-independent function so the rules
//! it emits are asserted on every host, not only on macOS: a wrong Seatbelt
//! profile is otherwise invisible until an acceptance run on the tier.
//!
//! ## What the tier guarantees, and what it does not
//! - **Path containment is kernel-enforced** by the Seatbelt profile, and
//!   `file-read*` is issued as granted-root subpath allows — never as a blanket
//!   read. A blanket grant under `(deny default)` is what previously made the
//!   whole disk readable to a spawned `bash` (`REQ-SEC-025`).
//! - **Child-process network denial is `best_effort`.** The rule binds the
//!   wrapped process; an escaped descendant is not separately confined. That
//!   residual is declared here and surfaced in `applied` by
//!   `crate::SeatbeltSandbox`, and a caller that requires `enforced` is refused
//!   rather than downgraded (`DEC-026`).

use std::path::Path;

use crate::error::SandboxError;
use crate::paths::{
    existing_runtime_base_directories, existing_runtime_base_files, materialize_deny,
};
use crate::profile::{FsProfile, NetworkPolicy};
use crate::provider::ResolvedProfile;

/// Escapes a path for a Seatbelt literal.
fn escape(path: &Path) -> String {
    path.to_string_lossy()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

/// Renders the Seatbelt profile for a resolved confinement plan.
///
/// # Errors
/// Returns [`SandboxError::ConfinementFailed`] when a deny glob cannot be
/// materialized, so a profile whose protections cannot be expressed is never
/// applied in weakened form (`ARCH/13` §Failure modes).
pub fn seatbelt_profile(resolved: &ResolvedProfile) -> Result<String, SandboxError> {
    if resolved.bare {
        return Ok(String::from("(version 1)\n(allow default)\n"));
    }
    let mut out = String::from("(version 1)\n(deny default)\n");
    // Process and kernel services the child needs to run at all. `file-read-metadata`
    // is a stat grant, not a content grant: the child can traverse a path it was
    // given without gaining a byte of the file behind it.
    out.push_str("(allow process-fork)\n(allow process-exec*)\n(allow sysctl-read)\n");
    out.push_str("(allow mach-lookup)\n(allow signal)\n(allow file-read-metadata)\n");

    // Reads are scoped to the granted roots plus the declared runtime base, as
    // subpath/literal allows.
    for root in &resolved.readable_roots {
        out.push_str(&format!(
            "(allow file-read* (subpath \"{}\"))\n",
            escape(root)
        ));
    }
    for directory in existing_runtime_base_directories() {
        out.push_str(&format!(
            "(allow file-read* (subpath \"{}\"))\n",
            escape(&directory)
        ));
    }
    for file in existing_runtime_base_files() {
        out.push_str(&format!(
            "(allow file-read* (literal \"{}\"))\n",
            escape(&file)
        ));
    }

    // Writes: only the writable roots, and only for a profile that grants them.
    if resolved.profile == FsProfile::WorkspaceWrite {
        for root in &resolved.writable_roots {
            out.push_str(&format!(
                "(allow file-write* (subpath \"{}\"))\n",
                escape(root)
            ));
        }
    }
    // A protected subpath stays read-only even inside a writable root, so a
    // write grant cannot rewrite the policy or install a hook that later runs
    // outside confinement.
    for protected in &resolved.protected {
        out.push_str(&format!(
            "(deny file-write* (subpath \"{}\"))\n",
            escape(protected)
        ));
    }
    // Deny globs are kernel-enforced read *and* write, so a denied path can
    // neither be read through a tool nor relocated out of the deny set and read
    // elsewhere. They are materialized over the granted roots: the runtime base
    // is a fixed allowlist of support data, so an operator deny glob cannot
    // name anything inside it.
    let mut scoped = resolved.writable_roots.clone();
    for root in &resolved.readable_roots {
        if !scoped.contains(root) {
            scoped.push(root.clone());
        }
    }
    for denied in materialize_deny(&scoped, &resolved.deny)? {
        out.push_str(&format!(
            "(deny file-read* (subpath \"{}\"))\n(deny file-write* (subpath \"{}\"))\n",
            escape(&denied),
            escape(&denied)
        ));
    }

    match resolved.network {
        NetworkPolicy::None => out.push_str("(deny network*)\n"),
        NetworkPolicy::Allowlist(_) | NetworkPolicy::Full => {
            out.push_str("(allow network*)\n")
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::paths::RUNTIME_BASE_FILES;
    use crate::profile::ConfinementProfile;

    fn plan(profile: &ConfinementProfile) -> ResolvedProfile {
        ResolvedProfile {
            backend: "seatbelt".to_owned(),
            profile: profile.profile,
            network: profile.network.clone(),
            workspace: profile.workspace.clone(),
            writable_roots: profile.writable_roots(),
            readable_roots: profile.readable_roots(),
            protected: profile.protected.clone(),
            deny: profile.deny.clone(),
            session_dir: profile.session_dir.clone(),
            limits: profile.limits,
            applied: Vec::new(),
            epoch: 1,
            bare: profile.profile == FsProfile::FullAccess,
        }
    }

    #[test]
    fn there_is_no_blanket_file_read_grant() {
        let dir = tempfile::tempdir().unwrap();
        let profile = ConfinementProfile::workspace_write(dir.path());
        let text = seatbelt_profile(&plan(&profile)).unwrap();
        assert!(text.starts_with("(version 1)\n(deny default)\n"), "{text}");
        assert!(
            !text
                .lines()
                .any(|line| line.trim() == "(allow file-read*)"),
            "a blanket read grant makes the whole disk readable: {text}"
        );
    }

    #[test]
    fn reads_are_granted_per_root_and_per_runtime_entry() {
        let dir = tempfile::tempdir().unwrap();
        let granted = tempfile::tempdir().unwrap();
        let profile =
            ConfinementProfile::workspace_write(dir.path()).with_read_root(granted.path());
        let text = seatbelt_profile(&plan(&profile)).unwrap();
        assert!(
            text.contains(&format!(
                "(allow file-read* (subpath \"{}\"))",
                dir.path().display()
            )),
            "{text}"
        );
        assert!(
            text.contains(&format!(
                "(allow file-read* (subpath \"{}\"))",
                granted.path().display()
            )),
            "{text}"
        );
        for directory in existing_runtime_base_directories() {
            assert!(
                text.contains(&format!(
                    "(allow file-read* (subpath \"{}\"))",
                    directory.display()
                )),
                "runtime base entry missing: {text}"
            );
        }
        for file in existing_runtime_base_files() {
            assert!(
                text.contains(&format!(
                    "(allow file-read* (literal \"{}\"))",
                    file.display()
                )),
                "runtime base file missing: {text}"
            );
        }
    }

    #[test]
    fn the_read_allowlist_never_covers_account_or_credential_material() {
        for forbidden in [
            "/etc/passwd",
            "/etc/shadow",
            "/etc/gshadow",
            "/etc/ssh",
            "/etc/ssl/private",
            "/home",
            "/root",
        ] {
            assert!(
                !RUNTIME_BASE_FILES.contains(&forbidden),
                "{forbidden} must not be runtime support data"
            );
            for directory in existing_runtime_base_directories() {
                assert!(
                    !directory.to_string_lossy().starts_with(forbidden),
                    "{} is under the forbidden {forbidden}",
                    directory.display()
                );
            }
        }
    }

    #[test]
    fn deny_globs_become_kernel_deny_rules_for_read_and_write() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".env"), "SECRET=1\n").unwrap();
        std::fs::create_dir_all(dir.path().join(".ssh")).unwrap();
        std::fs::write(dir.path().join(".ssh/id_rsa"), "KEY\n").unwrap();
        let profile = ConfinementProfile::workspace_write(dir.path())
            .with_deny("**/.env")
            .with_deny("**/.ssh");
        let text = seatbelt_profile(&plan(&profile)).unwrap();
        assert!(
            text.contains(&format!(
                "(deny file-read* (subpath \"{}\"))",
                dir.path().join(".env").display()
            )),
            "{text}"
        );
        assert!(
            text.contains(&format!(
                "(deny file-read* (subpath \"{}\"))",
                dir.path().join(".ssh").display()
            )),
            "{text}"
        );
        assert!(
            text.contains(&format!(
                "(deny file-write* (subpath \"{}\"))",
                dir.path().join(".ssh").display()
            )),
            "{text}"
        );
    }

    #[test]
    fn protected_subpaths_stay_read_only_inside_a_writable_root() {
        let dir = tempfile::tempdir().unwrap();
        let profile = ConfinementProfile::workspace_write(dir.path());
        let hooks = dir.path().join(".git/hooks");
        let text = seatbelt_profile(&plan(&profile)).unwrap();
        assert!(
            text.contains(&format!(
                "(deny file-write* (subpath \"{}\"))",
                hooks.display()
            )),
            "{text}"
        );
    }

    #[test]
    fn a_path_containing_a_quote_or_backslash_is_escaped() {
        assert_eq!(
            escape(Path::new("/w/or\"d\\here")),
            "/w/or\\\"d\\\\here",
            "an unescaped quote would terminate the literal and change the rule"
        );
    }

    #[test]
    fn network_none_denies_and_a_bare_plan_grants_nothing_to_constrain() {
        let dir = tempfile::tempdir().unwrap();
        let profile = ConfinementProfile::workspace_write(dir.path());
        let text = seatbelt_profile(&plan(&profile)).unwrap();
        assert!(text.contains("(deny network*)"), "{text}");

        let full = ConfinementProfile::full_access(dir.path());
        assert!(
            seatbelt_profile(&plan(&full)).unwrap().contains("(allow default)"),
            "a bare plan applies no confinement"
        );
    }

    #[test]
    fn a_read_only_profile_grants_no_writes() {
        let dir = tempfile::tempdir().unwrap();
        let profile = ConfinementProfile::read_only(dir.path());
        let text = seatbelt_profile(&plan(&profile)).unwrap();
        assert!(
            !text.contains("(allow file-write*"),
            "a read-only profile must not grant a write: {text}"
        );
    }
}
